project/datamanager/urls.py
from django.urls import path

from datamanager.views import *

urlpatterns = [
    path('importDSD/', import_DSD, name='import_DSD'),
    path('importDOCENTE/', importdocentesxls, name='import_DOCENTE'),
    path('importRUC/', import_RUC, name='import_RUC'),
    path('importSalas', import_salas, name='import_salas'),
    path('export/', export_pedidos_xls, name='export_pedidos_xls'),
    path('sucesso/', sucesso_view, name='sucesso'),
]

project/funcionariomanager/urls.py
from django.urls import path


from funcionariomanager.views import *

urlpatterns = [
    path('createAnoletivo/', create_anoletivo, name='create_anoletivo'),
    path('selectAnoLetivo/', selectanoletivo, name='select_ANOLETIVO'),
    path('sucesso/', sucesso_view, name='sucesso'),
    path('erro/', erro_view, name='erro'),
    path('delete_anoLetivo/<int:id>', delete_anoletivo, name="deleteAnoLetivo"),
    path('anoLetivo/', RenderAnoLetivo, name='list_anoletivo'),
    path('edit_anoLetivo/<int:id>', edit_anoletivo, name="editAnoLetivo"), 
    path('email_PCP/<int:ppd_ID>', emailPCP, name="emailPCP"),
    path('app/<int:user_id>', app_render.as_view(template_name="funcionariomanager/app.html"), name='app_render'),
    path('consult_pedidoSala/<int:pedidoID>', consult_pedidoSala, name='consult_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('consult_pedidoHorario/<int:pdd_id>', consult_pedidoHorario, name='consult_pedido'),
    path('consult_pedidoUnidadeCurricular/<int:id>', consult_unidadeCurricular, name='consult_pedidoUC'),
    path('confirmation/resolve/<int:pdd_id>', resolve_pedido, name='resolve_pedido'),    
    path('confirmation/link/<int:pdd_id>', link_pedido, name='link_pedido'),
    path('confirmation/cancel/<int:pdd_id>', cancela_pedido, name='cancela_pedido'),
    path('confirmation/desassocia/<int:pdd_id>', desassocia_pedido, name='desassocia_pedido'),
    path('rejection_message/', msg_motivo, name='rejection_message/')
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('api-auth', include('rest_framework.urls')),
    path('api/', include('todo_api.urls')),
    path('funcionariomanager/', include(('funcionariomanager.urls', 'funcionariomanager'), namespace='funcionariomanager')),
    path('datamanager/', include(('datamanager.urls', 'datamanager'), namespace='datamanager')),
    path('requestmanager/', include(('requestmanager.urls', 'requestmanager'), namespace='requestmanager')),
    path('statmanager/', include(('statmanager.urls', 'statmanager'), namespace='statmanager')),
    path('authmanager/', include(('authmanager.urls', 'authmanager'), namespace='authmanager')),
    #path('utilizadores/', include(('utilizadores.urls', 'utilizadores'), namespace='utilizadores')),
    path('admin/', admin.site.urls),
]

project/requestmanager/urls.py
from django.urls import path

from requestmanager.views import *

urlpatterns = [
    path('pedidoHorario/', create_pedidoHorario, name='create_pedidoHorario'),
    path('editarPedidoHorario/<int:pdd_id>', edit_pedidoHorario, name='edit_pedidoHorario'),
    # path('apagarPedidoHorario/<int:pdd_id>', delete_pedidoHorario, name='delete_pedidoHorario'),
    path('createpedidooutro/', create_pedidooutro, name='create_pedidooutro'),
    # path('deletepedidooutro/', delete_pedidooutro, name='delete_pedidooutro'),
    path('editpedidooutro/<int:pdd_id>', edit_pedidooutro, name='edit_pedidooutro'),
    path('create_pedidoUnidadeCurricular/', create_unidadeCurricular, name='create_unidadeCurricular'),
    # path('delete_pedidoUnidadeCurricular/<int:pedidoID>', delete_unidadeCurricular, name='delete_unidadeCurricular'),
    path('edit_pedidoUnidadeCurricular/<int:pedidoID>', edit_unidadeCurricular, name='edit_unidadeCurricular'),
    path('list_pedidoUnidadeCurricular/<int:user_id>', app_renderUC.as_view(template_name="requestmanager/list_unidadecurricular.html"), name='list_unidadeCurricular'),
    path('list_salas/<int:user_id>', app_renderSalas.as_view(template_name="requestmanager/list_salas.html"), name='list_salas'),
    path('list_horario/<int:user_id>', app_renderHorario.as_view(template_name="requestmanager/list_horario.html"), name='list_horario'),
    path('list_outros/<int:user_id>', app_renderOutros.as_view(template_name="requestmanager/list_outros.html"), name='list_outros'),
    # path('delete_pedidoSala/', delete_pedidoSala, name='delete_pedidoSala'),
    path('create_pedidoSala/', create_pedidoSala, name='create_pedidoSala'),
    path('edit_pedidoSala/<int:pedidoID>', edit_pedidoSala, name='edit_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('delete_pedido/<int:pdd_id>', delete_pedido, name='delete_pedido'),
    path('app/<int:user_id>', app_render.as_view(template_name="requestmanager/app.html"), name='app_render'),
    path('consult_pedidoSala/<int:pedidoID>', consult_pedidoSala, name='consult_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('consult_pedidoHorario/<int:pdd_id>', consult_pedidoHorario, name='consult_pedido'),
    path('consult_pedidoUnidadeCurricular/<int:id>', consult_unidadeCurricular, name='consult_pedidoUC'),
    path('delete_pedido/<int:id>', delete_pedido, name='delete_pedido'),
    path('sucesso/', sucesso_view, name='sucesso'),
    path('welcome/', welcome_page_view, name='welcome_page')
]

project/statmanager/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('funcionarios_stats/', funcionarios_stats, name='funcionarios_stats'),
    path('chart_pedidos/', chart.as_view(), name='chart_pedidos'),
    path('chart_data/', chartPedidos.as_view(), name='chart_data'),
    
    path('funcionarios_data/', average_pedidos_timerange, name='fixe'),
    path('pedidos_media/', pedidos_media, name='pedidos_media'),
    path('lchartdata/', getLineChartData, name ='lchartdata'),
    path('lchartdata2/', getLineChartAfterCheck, name='lchartdata2')
]

project/statmanager/models.py
from django.db import models

# Create your models here.

project/statmanager/forms.py
from datetime import date
from django import forms
from django.forms import DateInput, ModelForm, inlineformset_factory, BaseInlineFormSet, formset_factory
from requestmanager.models import *


class stat_form(forms.Form):
    
    TipoPedidoEntries = TipoPedido.objects.values_list('id', 'nome')
    TipoPedidoEntries = list(TipoPedidoEntries)
    todos = (5, 'Todos')
    TipoPedidoEntries.append(todos)
    
    print(TipoPedidoEntries)
    
    AnoLetivoEntries = AnoLetivo.objects.values_list('id', 'nome')
    AnoLetivoEntries = list(AnoLetivoEntries)
    
    ano_letivo = forms.ChoiceField(label="Ano Letivo", choices=AnoLetivoEntries)
    tipo = forms.ChoiceField(label="Tipo de pedido", choices=TipoPedidoEntries)
    
    
    

project/statmanager/views.py
import math
import time
import json
from django.views import View

import pytz
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from requestmanager.models import *
from .forms import *
from rest_framework.views import APIView
from rest_framework.response import Response
from requestmanager.views import selectanoletivo

def funcionarios_stats(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario").exists():
        return redirect('/requestmanager/welcome/')
    return render(request, 'statmanager/average_pedido_form.html', {'error': ''})


def average_pedidos_timerange(request):
    if request.method == 'POST':
        print(request.body.decode("utf-8"))
        t = json.loads(request.body.decode("utf-8"))
        print(t)
        data_resolvidos = []
        data_aceites = []
        data_pendentes = []
        data_cancelados = []
        labels = []

        pendente = EstadoPedido.objects.get(pk=1)
        aceite = EstadoPedido.objects.get(pk=2)
        resolvido = EstadoPedido.objects.get(pk=3)
        cancelado = EstadoPedido.objects.get(pk=4)

        data_inicio = datetime.strptime(t['data_inicio'], '%Y-%m-%d').date().isoformat()
        data_fim = datetime.strptime(t['data_fim'], '%Y-%m-%d').date().isoformat()

        print(t['f'])
        lista = json.loads(t['f'])
        for obj in lista:
            print(obj)
            id_F = obj['id']
            funcionario = Funcionario.objects.get(pk=id_F)
            labels.append(funcionario.username)

            p2 = len(Pedido.objects.filter(responsavel=funcionario, estado=aceite, dataatribuicao__gte=data_inicio,
                                           dataatribuicao__lte=data_fim))
            p3 = len(Pedido.objects.filter(responsavel=funcionario, estado=resolvido, dataresolvido__gte=data_inicio,
                                           dataresolvido__lte=data_fim))
            p4 = len(Pedido.objects.filter(responsavel=funcionario, estado=cancelado, dataresolvido__gte=data_inicio,
                                           dataresolvido__lte=data_fim))

            data_resolvidos.append(p3)
            data_cancelados.append(p4)
            data_aceites.append(p2)

        data = {
            'labels': labels,
            'chart_labels': 'my_data',
            'data_resolvidos': data_resolvidos,
            'data_aceites': data_aceites,
            'data_cancelados': data_cancelados
        }
        return JsonResponse(data)


def pedidos_media(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario").exists():
        return redirect('/requestmanager/welcome/')

    anoletivo = request.GET.get('anoletivo')
    tipo = request.GET.get('tipo')
    first_date = request.GET.get('first_date')
    second_date = request.GET.get('second_date')
    
    anoletivo = AnoLetivo.objects.get(nome=anoletivo)
    if tipo == "Todos":
        tipo = "Todos"
    else:
        tipo = TipoPedido.objects.get(nome=tipo)


    estado = EstadoPedido.objects.get(pk=3)

    if first_date == '' or second_date == '':
        if tipo == "Todos":
            pedidos = Pedido.objects.filter(anoletivo = anoletivo, estado=estado)
        else:
            pedidos = Pedido.objects.filter(anoletivo= anoletivo, tipo = tipo, estado=estado)
    else:
        data_inicio = datetime.strptime(first_date, '%Y-%m-%d').date().isoformat()
        data_fim = datetime.strptime(second_date, '%Y-%m-%d').date().isoformat()
        if tipo == "Todos":
            pedidos = Pedido.objects.filter(anoletivo = anoletivo, estado=estado, dataresolvido__gte=data_inicio,
                                            dataresolvido__lte=data_fim)
        else:
            pedidos = Pedido.objects.filter(anoletivo= anoletivo, tipo = tipo, estado=estado, dataresolvido__gte=data_inicio,
                                            dataresolvido__lte=data_fim)


    media = get_media(pedidos)
    
    if (media == 0):
        return JsonResponse(str(0), safe=False)

    days = math.floor(media / (24*60))
    leftover_minutes = media % (24*60)
    hours = math.floor(leftover_minutes / 60)
    mins = math.floor(media - (days*1440) - (hours*60))
    if(days == 1):
        time = f'{days} dia, {hours}h:{mins}m'
    else:
        time = f'{days} dias, {hours}h:{mins}m'


    return JsonResponse(time, safe=False)


# DAR PARSE DE DAYS
def get_media(pedidos):
    soma = 0
    for pedido in pedidos:
        dateString = pedido.tempoprocesso
        check = True
        index = pedido.tempoprocesso.find("days")
        if (index == -1 ):
            index = pedido.tempoprocesso.find("day")
            check = False
        print("asdasdasdasdasdads")
        print (index)
        total_min = 0
        if (index != -1):
            days = int(pedido.tempoprocesso[0:index])
            if (check):
                dateString = pedido.tempoprocesso[index + 6:len(pedido.tempoprocesso)]
            else: 
                dateString = pedido.tempoprocesso[index + 5:len(pedido.tempoprocesso)]
            total_min += days * 24 * 60
        datet = datetime.strptime(dateString, '%H:%M:%S.%f')
        total_min += datet.hour * 60 + datet.minute
        soma += total_min
    if len(pedidos) == 0:
        return 0
    return soma / len(pedidos)


alChoices = list(AnoLetivo.objects.all())
tipos = list(TipoPedido.objects.all())


class chart(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('/requestmanager/welcome/')
        return render(request, 'statmanager/chart_pedidos.html', {'tipos': tipos, 'alChoices': alChoices})


class chartPedidos(APIView):

    def get(self, request, format=None):
        labels = [
            'Outros',
            'SALAS',
            'UC',
            'Horarios'
        ]
        chartLabel = "my data"

        pendente = EstadoPedido.objects.get(pk=1)
        aceite = EstadoPedido.objects.get(pk=2)
        resolvido = EstadoPedido.objects.get(pk=3)

        n_pdd_outros = len(list(Pedido.objects.filter(tipo=1)))
        n_pdd_salas = len(list(Pedido.objects.filter(tipo=2)))
        n_pdd_uc = len(list(Pedido.objects.filter(tipo=3)))
        n_pdd_hora = len(list(Pedido.objects.filter(tipo=4)))

        pedidos_pedentes = Pedido.objects.filter(estado=pendente)
        pedidos_aceites = Pedido.objects.filter(estado=aceite)
        pedidos_resolvidos = Pedido.objects.filter(estado=resolvido)

        pedidosOutros_pedentes = len(list(Pedido.objects.filter(estado=pendente, tipo=1)))
        pedidosOutros_aceites = len(list(Pedido.objects.filter(estado=aceite, tipo=1)))
        pedidosOutros_resolvidos = len(list(Pedido.objects.filter(estado=resolvido, tipo=1)))

        pedidosSalas_pedentes = len(list(Pedido.objects.filter(estado=pendente, tipo=2)))
        pedidosSalas_aceites = len(list(Pedido.objects.filter(estado=aceite, tipo=2)))
        pedidosSalas_resolvidos = len(list(Pedido.objects.filter(estado=resolvido, tipo=2)))

        pedidosUcs_pedentes = len(list(Pedido.objects.filter(estado=pendente, tipo=3)))
        pedidosUcs_aceites = len(list(Pedido.objects.filter(estado=aceite, tipo=3)))
        pedidosUcs_resolvidos = len(list(Pedido.objects.filter(estado=resolvido, tipo=4)))

        pedidosHorarios_pedentes = len(list(Pedido.objects.filter(estado=pendente, tipo=4)))
        pedidosHorarios_aceites = len(list(Pedido.objects.filter(estado=aceite, tipo=4)))
        pedidosHorarios_resolvidos = len(list(Pedido.objects.filter(estado=resolvido, tipo=4)))

        chartdata = [n_pdd_outros, n_pdd_salas, n_pdd_uc, n_pdd_hora]
        chartdata_pendentes = [pedidosOutros_pedentes, pedidosSalas_pedentes, pedidosUcs_pedentes,
                               pedidosHorarios_pedentes]
        chartdata_aceites = [pedidosOutros_aceites, pedidosSalas_aceites, pedidosUcs_aceites, pedidosHorarios_aceites]
        chartdata_resolvidos = [pedidosOutros_resolvidos, pedidosSalas_resolvidos, pedidosUcs_resolvidos,
                                pedidosHorarios_resolvidos]

        data = {
            "labels": labels,
            "chartLabel": chartLabel,
            "chartdata": chartdata,
            "chartdata_pendentes": chartdata_pendentes,
            "chartdata_aceites": chartdata_aceites,
            "chartdata_resolvidos": chartdata_resolvidos
        }
        return Response(data)


MESES = ["JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO",
         "NOVEMBRO", "DEZEMBRO"]


def getLineChartData(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario").exists():
        return redirect('/requestmanager/welcome/')

    return startupChart(selectanoletivo())


def getLineChartAfterCheck(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario").exists():
        return redirect('/requestmanager/welcome/')

    if request.method == 'GET':
        anoletivo = request.GET.get('anoletivo')
        anoletivo = AnoLetivo.objects.get(nome=anoletivo)
    return startupChart(anoletivo)


def startupChart(anoletivo):
    num_pdd_criados = []
    num_pdd_resolvidos = []
    labels = []
    color1 = []
    color2 = []

    start = anoletivo.datainicio.month
    end = anoletivo.datafim.month

    year1 = anoletivo.datainicio.year
    year2 = anoletivo.datafim.year

    checky1 = year1
    checky2 = year2

    switch = False
    while (start < end or checky1 < checky2):
        if (anoletivo.datafim.year > anoletivo.datainicio.year and start == 12):
            start = 0
            checky1 += 1
            switch = True
        if (switch):
            num1 = len(Pedido.objects.filter(datacriacao__month=start, datacriacao__year=year2))
            num2 = len(Pedido.objects.filter(dataresolvido__month=start, datacriacao__year=year2))
        else:

project/statmanager/templates/statmanager/average_pedido_form.html
{% extends 'funcionariomanager/layout.html' %}
{% load static %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<h1 style="text-align: center; font-weight: bold; font-size: larger;">Estatísticas de Funcionários</h1><br>
    <div id="table">
            <div v-if="hasErrors" class="has-text-centered">
                <span class="">[[errorMessage]]</span>
            </div>
            <form id="form">
                Data inicio:
                <input type="date" v-model="data_inicio">
                Data fim:
                <input type="date" v-model="data_fim">
                <div class="block columns is-centered">
                    <div class="column">
                        <table class="table">
                            <thead>
                            <tr>
                                <th style="width:1%"><input type="checkbox" @change="handleAllCheck">All</th>
                                <th style="width:10%">Funcionários</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="(value, i) in funcionarios" :key="i">
                                <td>
                                    <input v-if="checkboxes[i]" checked type="checkbox" @change="handleCheck(value, i)">
                                    <input v-else type="checkbox" @change="handleCheck(value, i)">
                                </td>
                                <td>
                                    <span>[[ value.username ]]</span>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </form>
            <div class="block">
                <button class="button is-primary" @click="handleSubmit()"> Get </button>
            </div>
            <select @change="onChange($event)">
                <option value="Resolvidos"> Resolvidos </option>
                <option value="Aceites"> Aceites </option>
                <option value="Cancelados"> Cancelados </option>
            </select>
        </div>
    </div>
    <div style="display:flex; align-item:center; justify-content:center">
        <canvas style="height:50px; width: 100px;" id="myPolarChart"></canvas>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script>
        var myPolarChart
        var chartData
        var app = new Vue({
            delimiters: ["[[", "]]"],
            el: '#table',
            data() {
                return {
                    funcionarios: [],
                    selected: [],
                    checkboxes: [],
                    data_inicio: '',
                    data_fim: '',
                    allChecked: false,
                    hasErrors: true,
                    errorMessage: '',
                    response: '',
                    change: false
                }
            },
            async created() {
                await this.fetchData();
            },
            methods: {
                async fetchData() {
                    this.funcionarios = await axios.get('http://127.0.0.1:8000/api/funcionarios/')
                    this.funcionarios = this.funcionarios.data
                    for (let i = 0; i < this.funcionarios.length; i++) this.$set(this.checkboxes, i, false)
                },
                handleAllCheck() {
                    this.funcionarios.forEach(fun => {
                        let index = this.selected.indexOf(fun);
                        if (index === -1) this.selected.push(fun)
                    })
                    this.allChecked = !this.allChecked
                    for (let i = 0; i < this.checkboxes.length; i++) this.$set(this.checkboxes, i, this.allChecked)
                    console.log(this.selected)
                    console.log(this.checkboxes)
                },
                handleCheck(value, i) {
                    this.allChecked = false
                    console.log(value)
                    let index = this.selected.indexOf(value);
                    if (index !== -1) this.selected.splice(index, 1)
                    else this.selected.push(value)
                    this.checkboxes[i] = !this.checkboxes[i]
                    console.log(this.selected)
                    console.log(this.checkboxes)
                },
                async handleSubmit() {
                    var endpoint = 'http://127.0.0.1:8000/statmanager/funcionarios_data/'
                    var selected = JSON.stringify(this.selected)
                    console.log('AAAAAAAAAAAAAAAAAAAAAAAAAA')
                    console.log(selected)
                    
                    data = await axios.post(endpoint, {
                        'f': selected, 'data_inicio': this.data_inicio, 'data_fim': this.data_fim
                    }, {
                        xsrfCookieName: 'csrftoken',
                        xsrfHeaderName: 'X-CSRFTOKEN',
                    }
                    )
                    console.log(data.data)
                    chartData = data.data
                    this.drawGraph(data.data)
                    //this.$http.post(endpoint, selected).then(res => this.drawGraph(res))
                    /*$.ajax({
                        method: "GET",
                        url: endpoint,
                        data: {
                          'f': selected,
                        },
                        success: function (data) {
                            this.drawGraph(data)
                            
                        },
                        error: function(data) {
                            console.log(':(')
                            console.log(data); 
                              
                        }
                    });*/
                },

                drawGraph(data) {
                    if (this.change == false) {
                        var labels = data.labels;
                        var chartLabel = data.chart_labels;
                        var chartdata = data.data_resolvidos;
                        var ctx = document.getElementById('myPolarChart')
                        myPolarChart = new Chart(ctx, {
                            type: 'polarArea',
                            data: {
                            labels: labels,
                            datasets: [{
                                label: chartLabel,
                                data: chartdata,
                                backgroundColor: [
                                'rgba(255, 99, 132, 0.5)',
                                'rgba(54, 162, 235, 0.5)',
                                'rgba(255, 206, 86, 0.5)',
                                'rgba(75, 192, 192, 0.5)',
                                'rgba(153, 102, 255, 0.5)',
                                'rgba(255, 159, 64, 0.5)'
                                ],
                                borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                                ],
                                borderWidth: 1.5
                            }]
                            },
                            options: {
                            responsive: true,
                            
                            }
                        });
                        this.change = true
                    } else {
                        myPolarChart.data.datasets[0].data = data.data_resolvidos
                        myPolarChart.data.labels = data.labels
                        myPolarChart.update() 
                    }
                },

                checkErrors() {
                    if (this.data_inicio === '' || this.data_fim === '') {
                        this.errorMessage = "Deve indicar duas datas."
                        return false
                    }

                    if (this.data_inicio > this.data_fim) {
                        this.errorMessage = "A data final deve ser posterior à data inicial."
                        return false
                    }

                    if (this.selected.length == 0) {
                        this.errorMessage = "Deve selecionar pelo menos um funcionário."
                        return false
                    }
                    return this.handleSubmit()
                },
                onChange(event){
                    var change = event.target.value
                    {#console.log(change)#}
                    if (change == "Resolvidos"){myPolarChart.data.datasets[0].data = chartData.data_resolvidos}
                    if(change == "Aceites"){myPolarChart.data.datasets[0].data = chartData.data_aceites}
                    if(change == "Cancelados"){myPolarChart.data.datasets[0].data = chartData.data_cancelados}

                    myPolarChart.update()
                },

            },
        })

        
    </script>

{% endblock content %}

project/statmanager/templates/statmanager/navbar.html
{% load static %}
<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item logo" href="{% url 'requestmanager:app_render' %}">
          <img src="{% static 'img/logo-navbar.png' %}" alt="UALG">
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Pedidos</a>
            <div class="navbar-dropdown">
              <a href="{% url 'requestmanager:list_outros' %}" class="navbar-item">Pedidos Outros</a>
              <a href="{% url 'requestmanager:list_horario' %}" class="navbar-item">Pedido Horário</a>
              <a href="{% url 'requestmanager:list_salas' %}" class="navbar-item">Pedido Sala</a>
              <a href="{% url 'requestmanager:list_unidadeCurricular' %}" class="navbar-item">Pedido Unidade Curricular</a>
            </div>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Import/Export</a>
            <div class="navbar-dropdown">
              <a href="{% url 'datamanager:export_pedidos_xls' %}" class="navbar-item">Export Pedidos</a>
              <a href="{% url 'datamanager:import_RUC' %}" class="navbar-item">Import RUC</a>
              <a href="{% url 'datamanager:import_DSD' %}" class="navbar-item">Import DSD</a>
              <a href="{% url 'datamanager:import_salas' %}" class="navbar-item">Import Salas</a>
              <a href="{% url 'datamanager:import_DOCENTE' %}" class="navbar-item">Import DOCENTE</a>
            </div>
          </div>
            
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Funcionários</a>
            <div class="navbar-dropdown">
              <a href="{% url 'funcionariomanager:create_anoletivo' %}" class="navbar-item">Criar Ano Letivo</a>
              <a href="{% url 'funcionariomanager:list_anoletivo' %}" class="navbar-item">Listar Anos Letivos</a>
            </div> 
          </div>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Estatisticas</a>
            <div class="navbar-dropdown">
              <a href="{% url 'statmanager:pedidos_media' %}" class="navbar-item"> Media de pedidos </a>
              <a href="{% url 'statmanager:funcionarios_stats' %}" class="navbar-item"> Média de funcionários </a>
            </div>
          </div>

        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <a class="navbar-item">
              Criar Utilizador
            </a>
            <a class="navbar-item">
              Login
            </a>
          </div>
        </div>
    </div>
</nav>