project/authmanager/urls.py
from django.urls import path
from authmanager.views import *


urlpatterns = [
    #path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path("login/", login_action, name="login"),
    path('mensagem/<int:id>', mensagem,name='mensagem'),   
    
    path('escolher_perfil/', escolher_perfil, name='escolher_perfil'),
    path('register_user/<int:id>', criar_utilizador, name='register_user'),
    path('concluir_registo/<int:id>', concluir_registo, name='concluir_registo'),
    
    path('ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('api-auth', include('rest_framework.urls')),
    path('api/', include('todo_api.urls')),
    path('funcionariomanager/', include(('funcionariomanager.urls', 'funcionariomanager'), namespace='funcionariomanager')),
    path('datamanager/', include(('datamanager.urls', 'datamanager'), namespace='datamanager')),
    path('requestmanager/', include(('requestmanager.urls', 'requestmanager'), namespace='requestmanager')),
    path('statmanager/', include(('statmanager.urls', 'statmanager'), namespace='statmanager')),
    path('authmanager/', include(('authmanager.urls', 'authmanager'), namespace='authmanager')),
    #path('utilizadores/', include(('utilizadores.urls', 'utilizadores'), namespace='utilizadores')),
    path('admin/', admin.site.urls),
]

project/authmanager/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Faculdade(models.Model):
    nome = models.CharField(db_column='nome', max_length=255, blank=False, null=False)

    def __str__(self):
        return str(self.nome)
    
    class Meta:
        managed = True
        db_table = 'Faculdade'


class Departamento(models.Model):
    nome = models.CharField(db_column='nome', max_length=255, blank=False, null=False)
    faculdadeid = models.ForeignKey('Faculdade', models.CASCADE)
    
    def __str__(self):
        return str(self.nome)
    

    class Meta:
        managed = True
        db_table = 'Departamento'


class Utilizador(User):
    contacto = PhoneNumberField(max_length=20, blank=False, null=False)
    valido = models.CharField(max_length=255, blank=False, null=False)

    def getProfiles(self):
        type = ''
        if ProfessorUniversitario.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='ProfessorUniversitario')
        if Funcionario.objects.filter(utilizador_ptr_id=self):
            type = self.concat(type=type, string='Funcionario')
        return type

    def concat(self, type, string):
        if type == '':
            type = string
        else:
            type += ', ' + string
        return type

    @property
    def firstProfile(self):
        return self.getProfiles().split(' ')[0]

    def getUser(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name="Funcionario").exists():
            result = Funcionario.objects.get(id=self.id)
        elif user.groups.filter(name="ProfessorUniversitario").exists():
            result = ProfessorUniversitario.objects.get(id=self.id)
        else:
            result = None
        return result

    def getProfile(self):
        user = User.objects.get(id=self.id)
        if user.groups.filter(name="ProfessorUniversitario").exists():
            result = "ProfessorUniversitario"
        elif user.groups.filter(name="Funcionario").exists():
            result = "Funcionario"
        else:
            result = None
        return result

    # def emailValidoUO(self, uo):
    #     user = User.objects.get(email=self.email)
    #     if user.groups.filter(name="ProfessorUniversitario").exists():
    #         utilizador = ProfessorUniversitario.objects.get(email=self.email)
    #     elif user.groups.filter(name="Funcionario").exists():
    #         utilizador = Funcionario.objects.get(email=self.email)
    #     else:
    #         return False
    #     if utilizador.faculdade == uo:
    #         return True
    #     else:
    #         return False

    def emailValidoParticipante(self):
        user = User.objects.get(email=self.email)
        if user.groups.filter(name="Administrador").exists():
            return True
        else:
            return False

    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        managed = True
        db_table = 'Utilizador'


class ProfessorUniversitario(Utilizador):
    gabinete = models.CharField(
        db_column='Gabinete', max_length=255, blank=False, null=False)

    faculdade = models.ForeignKey('Faculdade', models.CASCADE)

    departamento = models.ForeignKey('Departamento', models.CASCADE)

    def __str__(self):
        return str(super().full_name)
        #return str(self.gabinete) + ' ' + str(self.faculdade) + ' ' + str(self.departamento)

    class Meta:
        managed = True
        db_table = 'ProfessorUniversitario'


class Funcionario(Utilizador):
    gabinete = models.CharField(db_column='Gabinete', max_length=255, blank=False, null=False)
    faculdade = models.ForeignKey('Faculdade', models.CASCADE)

    def __str__(self):
        return str(super().full_name)
        #return str(self.gabinete) + ' ' + str(self.faculdade)

    class Meta:
        managed = True
        db_table = 'Funcionario'

project/authmanager/forms.py
from .models import *
from requestmanager.models import *
from django import forms
from django.forms import CharField, PasswordInput, TextInput, ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from authmanager.models import Faculdade, Funcionario, ProfessorUniversitario, Departamento



class LoginForm(AuthenticationForm):
    username=CharField(widget=TextInput(attrs={'class':'input','style':''}), label="Nome de Utilizador", max_length=255, required=False)
    password=CharField(widget=PasswordInput(attrs={'class':'input','style':''}), label= 'Senha', max_length=255, required=False)


class register_form(forms.Form):
    ni = forms.IntegerField(label="Numero de indentificação", required=True)
    email = forms.EmailField(label="Email", required=True)
    password = forms.CharField(label="Password", required=True, widget=forms.PasswordInput)


# class AdministradorRegisterForm(UserCreationForm):
#     class Meta:
#         model = Administrador
#         fields = ('username', 'password1', 'password2', 'email',
#                   'first_name', 'last_name', 'contacto', 'gabinete')
#
#     def clean(self):
#         username = self.cleaned_data.get('username')
#         password1 = self.cleaned_data.get('password1')
#         password2 = self.cleaned_data.get('password2')
#         email = self.cleaned_data.get('email')
#         first_name = self.cleaned_data.get('first_name')
#         last_name = self.cleaned_data.get('last_name')
#         contacto = self.cleaned_data.get('contacto')
#         gabinete = self.cleaned_data.get('gabinete')
#         erros = []
#         if email == "" or first_name == "" or last_name == "" or username == None or gabinete == None:
#             raise forms.ValidationError(f'Todos os campos são obrigatórios!')
#
#         if username and User.objects.filter(username=username).exists():
#             erros.append(forms.ValidationError(f'O username já existe'))
#
#         if password1 == None or password2 == None:
#             if password1 == None:
#                 raise forms.ValidationError(f'Todos os campos são obrigatórios!')
#             if password1 == None:
#                 raise forms.ValidationError(f'Todos os campos são obrigatórios!')
#             else:
#                 erros.append(forms.ValidationError(f'As palavras-passe não correspondem'))
#
#         if email and User.objects.filter(email=email).exclude(username=username).exists():
#             raise forms.ValidationError(f'O email já existe')
#         elif email == None:
#             erros.append(forms.ValidationError(f'O email é inválido'))
#
#         if contacto == None:
#             erros.append(forms.ValidationError(f'Preencha corretamente o contacto'))
#         if len(erros) > 0:
#             raise ValidationError([erros])


class ProfessorUniversitarioRegisterForm(UserCreationForm):
    class Meta:
        model = ProfessorUniversitario
        fields = ('username', 'password1', 'password2', 'email',
                  'first_name', 'last_name', 'contacto', 'gabinete', 'faculdade', 'departamento')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['departamento'].queryset = Departamento.objects.none()

        if 'faculdade' in self.data:
            try:
                faculdadeid = int(self.data.get('faculdade'))
                self.fields['departamento'].queryset = Departamento.objects.filter(
                    faculdadeid=faculdadeid).order_by('nome')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['departamento'].queryset = self.instance.faculdade.departamento_set.order_by('nome')

    def clean(self):
        username = self.cleaned_data.get('username')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        email = self.cleaned_data.get('email')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        contacto = self.cleaned_data.get('contacto')
        gabinete = self.cleaned_data.get('gabinete')
        faculdade = self.cleaned_data.get('faculdade')
        departamento = self.cleaned_data.get('departamento')
        erros = []
        if email == "" or first_name == "" or last_name == "" or username is None or gabinete is None or faculdade is None or departamento is None:
            raise forms.ValidationError(f'Todos os campos são obrigatórios!')

        if username and User.objects.filter(username=username).exists():
            erros.append(forms.ValidationError(f'O username já existe'))

        if password1 is None or password2 is None:
            if password1 is None:
                raise forms.ValidationError(f'Todos os campos são obrigatórios!')
            if password1 is None:
                raise forms.ValidationError(f'Todos os campos são obrigatórios!')
            else:
                erros.append(forms.ValidationError(f'As palavras-passe não correspondem'))

        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(f'O email já existe')
        elif email is None:
            erros.append(forms.ValidationError(f'O email é inválido'))

        if contacto is None:
           erros.append(forms.ValidationError(f'Preencha corretamente o contacto'))
        print(contacto)
        print(erros)
        if len(erros) > 0:
            raise ValidationError([erros])


class FuncionarioRegisterForm(UserCreationForm):
    class Meta:
        model = Funcionario
        fields = ('username', 'password1', 'password2', 'email',
                  'first_name', 'last_name', 'contacto', 'gabinete', 'faculdade')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data.get('username')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        email = self.cleaned_data.get('email')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        contacto = self.cleaned_data.get('contacto')
        gabinete = self.cleaned_data.get('gabinete')
        faculdade = self.cleaned_data.get('faculdade')
        erros = []
        if email == "" or first_name == "" or last_name == "" or username is None or gabinete is None or faculdade is None:
            raise forms.ValidationError(f'Todos os campos são obrigatórios!')

        if username and User.objects.filter(username=username).exists():
            erros.append(forms.ValidationError(f'O username já existe'))

        if password1 is None or password2 is None:
            if password1 is None:
                raise forms.ValidationError(f'Todos os campos são obrigatórios!')
            if password1 is None:
                raise forms.ValidationError(f'Todos os campos são obrigatórios!')
            else:
                erros.append(forms.ValidationError(f'As palavras-passe não correspondem'))

        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(f'O email já existe')
        elif email is None:
            erros.append(forms.ValidationError(f'O email é inválido'))

        if contacto is None:
            erros.append(forms.ValidationError(f'Preencha corretamente o contacto'))
        if len(erros) > 0:
            raise ValidationError([erros])

project/authmanager/templates/authmanager/register_user.html
{% extends 'requestmanager/layout.html' %}
{% load static %}

{% block content %}
    <div>
        <div style="padding: 3rem 2vw 1rem;">

            <div class="steps is-success">

                <div class="step-item is-completed is-success">

                    <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-account"></i>

                    </span>

                    </div>

                    <div class="step-details">

                        <p class="step-title">Escolher Perfil</p>

                    </div>

                </div>

                <div class="step-item is-completed is-success">

                    <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-circle-edit-outline mdi-24px"></i>

                    </span>

                    </div>


                    <div class="step-details">

                        <p class="step-title">Preencher Campos</p>

                    </div>

                </div>


                <div class="step-item is-success">

                    <div class="step-marker">

                    <span class="icon">

                        <i class="mdi mdi-check"></i>

                    </span>

                    </div>

                    <div class="step-details">

                        <p class="step-title">Concluir</p>

                    </div>

                </div>
            </div>


            {% if registo != 1 %}
                <form method="post">
                {% csrf_token %}
            {% elif registo == 1 %}
                <form method="post" id="ProfessorUniversitarioRegisterForm"
                      data-departamentos-url="{% url 'authmanager:ajax_load_departamentos' %}" novalidate>
                {% csrf_token %}
            {% endif %}


            <div style="padding: 1rem 2vw 0px;">
                <hr>
                <h2 class="title has-text-grey is-uppercase" style="font-size: 0.9rem;">
                    {{ perfil }}
                </h2>
                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Nome Próprio</label>
                            <div class="control is-clearfix">
                                <input name="first_name" class="input" id="id_first_name"
                                       value="{{ form.first_name.value|default_if_none:"" }}" style="" type="text"
                                       maxlength="255">
                                <!----> <!----> <!---->
                            </div>
                            <!---->
                        </div>
                    </div>
                    <div class="column">
                        <div class="field">
                            <label class="label">Apelido</label>
                            <div class="control is-clearfix">


                                <input name="last_name" class="input" id="id_last_name" style=""
                                       value="{{ form.last_name.value|default_if_none:"" }}" type="text"
                                       maxlength="255">
                            </div>
                            <!---->
                        </div>
                    </div>

                    <hr>
                </div>


                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Username</label>
                            <div class="control is-clearfix">
                                <input name="username" value="{{ form.username.value|default_if_none:"" }}"
                                       class="input" id="id_username" style="" type="text" maxlength="255">


                                <!----> <!----> <!---->
                            </div>
                            <!---->
                        </div>
                    </div>
                    <div class="column">
                        <div class="field">
                            <label class="label">Email</label>
                            <div class="control is-clearfix">
                                <input class="input" name="email" id="id_email"
                                       value="{{ form.email.value|default_if_none:"" }}" type="text" style=""
                                       maxlength="255"> <!----> <!----> <!---->
                            </div>
                            <!---->
                        </div>
                    </div>
                    <div class="column">
                        <div class="field">
                            <label class="label">Contacto</label>
                            <div class="control is-clearfix">

                                <input name="contacto" class="input" id="id_contacto"
                                       value="{{ form.contacto.value |default_if_none:"" }}" style="" type="text"
                                       maxlength="255">
                            </div>
                            <!---->
                        </div>
                    </div>
                    <hr>
                </div>

                <div class="columns">
                    <div class="column">
                        <div class="field">
                            <label class="label">Palavra-passe</label>
                            <div class="control is-clearfix">
                                <input name="password1" id="id_password1" class="input" style="" type="password"
                                       maxlength="255">


                                <!----> <!----> <!---->
                            </div>
                            <!---->
                        </div>
                    </div>
                    <div class="column">
                        <div class="field">
                            <label class="label">Confirmação da Palavra-passe</label>
                            <div class="control is-clearfix">
                                <input name="password2" id="id_password2" class="input" style="" type="password"
                                       maxlength="255"> <!----> <!----> <!---->
                            </div>
                            <!---->

                            <!---->
                        </div>
                    </div>
                    <hr>
                </div>
                {% if registo == 1 %}

                    <div class="columns">
                        <div class="column">
                            <div class="field">
                                <label class="label">Faculdade</label>
                                <div class="control is-clearfix">

                                    <div class="field">
                                        <!---->
                                        <div class="control is-expanded">
                                    <span class="select is-fullwidth is-empty">
                                        {{ form.faculdade }}
                                    </span>
                                            <!---->
                                        </div>
                                        <!---->
                                    </div>

                                </div>
                                <!---->
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label class="label">Departamento</label>
                                <div class="control is-clearfix">

                                    <div class="field">
                                        <!---->
                                        <div class="control is-expanded">
                                    <span class="select is-fullwidth is-empty">
                                        {{ form.departamento }}
                                    </span>
                                            <!---->
                                        </div>
                                        <!---->
                                    </div>

                                </div>
                                <!---->
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label class="label">Gabinete</label>
                                <div class="control is-clearfix">
                                    <input class="input" name="gabinete" id="id_gabinete"
                                           value="{{ form.gabinete.value|default_if_none:"" }}" type="text" style=""
                                           maxlength="255">
                                </div>
                                <!---->
                            </div>
                        </div>
                        <hr>
                    </div>
                {% elif registo == 2 %}
                    <div class="column">
                    <div class="column">
                        <div class="field">
                            <label class="label">Faculdade</label>
                            <div class="control is-clearfix">

                                <div class="field">
                                    <!---->
                                    <div class="control is-expanded">
                                    <span class="select is-fullwidth is-empty">
                                        {{ form.faculdade }}
                                    </span>
                                        <!---->
                                    </div>
                                    <!---->
                                </div>

                            </div>
                            <!---->
                        </div>
                        <div class="field">
                            <label class="label">Gabinete</label>
                            <div class="control is-clearfix">
                                <input class="input" name="gabinete" id="id_gabinete"
                                       value="{{ form.gabinete.value|default_if_none:"" }}" type="text" style=""
                                       maxlength="255">
                            </div>
                            <!---->
                        </div>
                    </div>
                {% endif %}
                <div style="margin-top:2%;text-align:center;position:center;">
                    <button type="button" value="Voltar" class="button is-outlined" style="margin-right:5%"
                            onclick="voltar()">Voltar
                    </button>
                    <button style="" type="submit" class="button is-success is-outlined">
                        <span>Confirmar</span>
                    </button>
                </div>
            </form>

            {% if msg %}
                <div style="margin-left:30%;margin-right:30%; margin-top:%">
                    <div style="margin-top:2%;text-align: center;position:center;">
                        <article class="message is-danger">
                            <div class="message-body">
                                <p style="text-align: center;">
                                    {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                            <p style="color: #ff0000; text-align:center">{{ error }}</p>
                                        {% endfor %}
                                    {% else %}

                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <p style="color: #ff0000;">{{ error }}</p>
                                            {% endfor %}
                                        {% endfor %}
                                    {% endif %}


                                </p>
                            </div>
                        </article>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


    <script script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"
            type="text/javascript"></script>

    <script>
        function voltar() {
            location.href = "http://127.0.0.1:8000/authmanager/escolher_perfil/"
        }

        {% if registo == 1 %}
            $("#id_faculdade").change(function () {
                var url = $("#ProfessorUniversitarioRegisterForm").attr("data-departamentos-url");
                console.log(url);
                var faculdadeid = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                        'faculdade': faculdadeid
                    },
                    success: function (data) {
                        $("#id_departamento").html(data);
                    }
                });

            });
        {% endif %}
    </script>

{% endblock content %}