project/authmanager/urls.py
from django.urls import path
from authmanager.views import *


urlpatterns = [
    #path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path("login/", login_action, name="login"),
    path('mensagem/<int:id>', mensagem,name='mensagem'),   
    
    path('escolher_perfil/', escolher_perfil, name='escolher_perfil'),
    path('register_user/<int:id>', criar_utilizador, name='register_user'),
    path('concluir_registo/<int:id>', concluir_registo, name='concluir_registo'),
    
    path('ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
]

project/datamanager/urls.py
from django.urls import path

from datamanager.views import *

urlpatterns = [
    path('importDSD/', import_DSD, name='import_DSD'),
    path('importDOCENTE/', importdocentesxls, name='import_DOCENTE'),
    path('importRUC/', import_RUC, name='import_RUC'),
    path('importSalas', import_salas, name='import_salas'),
    path('export/', export_pedidos_xls, name='export_pedidos_xls'),
    path('sucesso/', sucesso_view, name='sucesso'),
]

project/funcionariomanager/urls.py
from django.urls import path


from funcionariomanager.views import *

urlpatterns = [
    path('createAnoletivo/', create_anoletivo, name='create_anoletivo'),
    path('selectAnoLetivo/', selectanoletivo, name='select_ANOLETIVO'),
    path('sucesso/', sucesso_view, name='sucesso'),
    path('erro/', erro_view, name='erro'),
    path('delete_anoLetivo/<int:id>', delete_anoletivo, name="deleteAnoLetivo"),
    path('anoLetivo/', RenderAnoLetivo, name='list_anoletivo'),
    path('edit_anoLetivo/<int:id>', edit_anoletivo, name="editAnoLetivo"), 
    path('email_PCP/<int:ppd_ID>', emailPCP, name="emailPCP"),
    path('app/<int:user_id>', app_render.as_view(template_name="funcionariomanager/app.html"), name='app_render'),
    path('consult_pedidoSala/<int:pedidoID>', consult_pedidoSala, name='consult_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('consult_pedidoHorario/<int:pdd_id>', consult_pedidoHorario, name='consult_pedido'),
    path('consult_pedidoUnidadeCurricular/<int:id>', consult_unidadeCurricular, name='consult_pedidoUC'),
    path('confirmation/resolve/<int:pdd_id>', resolve_pedido, name='resolve_pedido'),    
    path('confirmation/link/<int:pdd_id>', link_pedido, name='link_pedido'),
    path('confirmation/cancel/<int:pdd_id>', cancela_pedido, name='cancela_pedido'),
    path('confirmation/desassocia/<int:pdd_id>', desassocia_pedido, name='desassocia_pedido'),
    path('rejection_message/', msg_motivo, name='rejection_message/')
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('api-auth', include('rest_framework.urls')),
    path('api/', include('todo_api.urls')),
    path('funcionariomanager/', include(('funcionariomanager.urls', 'funcionariomanager'), namespace='funcionariomanager')),
    path('datamanager/', include(('datamanager.urls', 'datamanager'), namespace='datamanager')),
    path('requestmanager/', include(('requestmanager.urls', 'requestmanager'), namespace='requestmanager')),
    path('statmanager/', include(('statmanager.urls', 'statmanager'), namespace='statmanager')),
    path('authmanager/', include(('authmanager.urls', 'authmanager'), namespace='authmanager')),
    #path('utilizadores/', include(('utilizadores.urls', 'utilizadores'), namespace='utilizadores')),
    path('admin/', admin.site.urls),
]

project/requestmanager/urls.py
from django.urls import path

from requestmanager.views import *

urlpatterns = [
    path('pedidoHorario/', create_pedidoHorario, name='create_pedidoHorario'),
    path('editarPedidoHorario/<int:pdd_id>', edit_pedidoHorario, name='edit_pedidoHorario'),
    # path('apagarPedidoHorario/<int:pdd_id>', delete_pedidoHorario, name='delete_pedidoHorario'),
    path('createpedidooutro/', create_pedidooutro, name='create_pedidooutro'),
    # path('deletepedidooutro/', delete_pedidooutro, name='delete_pedidooutro'),
    path('editpedidooutro/<int:pdd_id>', edit_pedidooutro, name='edit_pedidooutro'),
    path('create_pedidoUnidadeCurricular/', create_unidadeCurricular, name='create_unidadeCurricular'),
    # path('delete_pedidoUnidadeCurricular/<int:pedidoID>', delete_unidadeCurricular, name='delete_unidadeCurricular'),
    path('edit_pedidoUnidadeCurricular/<int:pedidoID>', edit_unidadeCurricular, name='edit_unidadeCurricular'),
    path('list_pedidoUnidadeCurricular/<int:user_id>', app_renderUC.as_view(template_name="requestmanager/list_unidadecurricular.html"), name='list_unidadeCurricular'),
    path('list_salas/<int:user_id>', app_renderSalas.as_view(template_name="requestmanager/list_salas.html"), name='list_salas'),
    path('list_horario/<int:user_id>', app_renderHorario.as_view(template_name="requestmanager/list_horario.html"), name='list_horario'),
    path('list_outros/<int:user_id>', app_renderOutros.as_view(template_name="requestmanager/list_outros.html"), name='list_outros'),
    # path('delete_pedidoSala/', delete_pedidoSala, name='delete_pedidoSala'),
    path('create_pedidoSala/', create_pedidoSala, name='create_pedidoSala'),
    path('edit_pedidoSala/<int:pedidoID>', edit_pedidoSala, name='edit_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('delete_pedido/<int:pdd_id>', delete_pedido, name='delete_pedido'),
    path('app/<int:user_id>', app_render.as_view(template_name="requestmanager/app.html"), name='app_render'),
    path('consult_pedidoSala/<int:pedidoID>', consult_pedidoSala, name='consult_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('consult_pedidoHorario/<int:pdd_id>', consult_pedidoHorario, name='consult_pedido'),
    path('consult_pedidoUnidadeCurricular/<int:id>', consult_unidadeCurricular, name='consult_pedidoUC'),
    path('delete_pedido/<int:id>', delete_pedido, name='delete_pedido'),
    path('sucesso/', sucesso_view, name='sucesso'),
    path('welcome/', welcome_page_view, name='welcome_page')
]

project/statmanager/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('funcionarios_stats/', funcionarios_stats, name='funcionarios_stats'),
    path('chart_pedidos/', chart.as_view(), name='chart_pedidos'),
    path('chart_data/', chartPedidos.as_view(), name='chart_data'),
    
    path('funcionarios_data/', average_pedidos_timerange, name='fixe'),
    path('pedidos_media/', pedidos_media, name='pedidos_media'),
    path('lchartdata/', getLineChartData, name ='lchartdata'),
    path('lchartdata2/', getLineChartAfterCheck, name='lchartdata2')
]

project/funcionariomanager/models.py
from django.db import models

# Create your models here.

project/funcionariomanager/forms.py
from .models import *
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class create_AnoLetivo(forms.Form):
    datainicio = forms.DateField(label="data", widget=DateInput)
    datafim = forms.DateField(label="data", widget=DateInput)

class edit_AnoLetivo(forms.Form):
    datainicio = forms.DateField(label="data", widget=DateInput)
    datafim = forms.DateField(label="data", widget=DateInput)
    
class email_PCP(forms.Form):
    assunto = forms.CharField(label='assunto', max_length=255, widget=forms.TextInput(attrs={"class":"block input"}))
    descricao = forms.CharField(label='descricao', widget=forms.Textarea(attrs={"class":"block textarea"}))
    
class messageForm(forms.Form):
    messagem = forms.CharField(label='messagem', max_length=255, widget=forms.TextInput(attrs={"class":"block textarea"}))

project/funcionariomanager/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from datetime import *
from datetime import date

from django_tables2 import *
from .tables import *

from django.contrib import messages
from django.core.mail import EmailMessage

from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from funcionariomanager.filters import *
from dateutil.relativedelta import relativedelta


#################################################
##### Ordem:                                #####
#####      -Envio de Informação para PCP    #####
#####      -Criar/ selecionar Ano Letivo    #####
#####      -Listar Ano Letivo               #####
#####      -Editar Ano Letivo               #####
#####      -Apagar Ano Letivo               #####
#####      -View Sucesso                    #####
#################################################

###################################################################################
######### Envio de Informação para PCP  ###########################################
######### Autor: André Oliveira         ###########################################
###################################################################################

def emailPCP(request, ppd_ID):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    pedido = Pedido.objects.get(id=ppd_ID)
    if request.method == 'POST':
        form = email_PCP(request.POST)
        if form.is_valid():
            assunto = request.POST.get('assunto')
            descricao = request.POST.get('descricao')
            link = ""
            if "Outros" in str(pedido.tipo):
                link = "link pedido: http://127.0.0.1:8000/funcionariomanager/consult_pedido/" + str(ppd_ID) + "\n"
            if "Salas" in str(pedido.tipo):
                link = "link pedido: http://127.0.0.1:8000/funcionariomanager/consult_pedidoSala/" + str(ppd_ID) + "\n"
            if "Unidades" in str(pedido.tipo):
                link = "link pedido: http://127.0.0.1:8000/funcionariomanager/consult_pedidoUnidadeCurricular/" + str(
                    ppd_ID) + "\n"
            if "Horários" in str(pedido.tipo):
                link = "link pedido: http://127.0.0.1:8000/funcionariomanager/consult_pedidoHorario/" + str(
                    ppd_ID) + "\n"
            nova_descricao = link + descricao
            email = EmailMessage(assunto, nova_descricao, 'a72707@ualg.pt', ['a72707@ualg.pt'])
            email.send()

            messages.info(request, 'Email enviado com sucesso')
            return redirect('/funcionariomanager/app/' + str(request.user.id))
    else:
        form = email_PCP()
    return render(request, 'funcionariomanager/email_PCP.html', {'form': form})


###################################################################################
######### Criar/ selecionar Ano letivo  ###########################################
######### Autor: António Madureira      ###########################################
###################################################################################

def create_anoletivo(request):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    if request.method == 'POST':
        form = create_AnoLetivo(request.POST)
        if form.is_valid():
            datainicio = form.cleaned_data['datainicio']
            datafim = form.cleaned_data['datafim']

            anoinicio = str(datainicio.year)
            anofim = str(datafim.year)

            minimo = str(datainicio + relativedelta(months=+8))
            maximo = str(datainicio + relativedelta(months=+12))

            if (datainicio >= datafim):
                messages.info(request, 'A data de inicio deve ser antes da data final!')
                return HttpResponseRedirect('/funcionariomanager/createAnoletivo')

            if not ((minimo <= str(datafim)) and (str(datafim) <= maximo)):
                messages.info(request, 'Os anos letivos devem ter um minimo de 8 meses e um maximo de um ano!')
                return HttpResponseRedirect('/funcionariomanager/createAnoletivo')

            name = str(anoinicio) + "-" + (str(anofim))[2:4]
            if AnoLetivo.objects.filter(nome=name).count():
                print("Erro Dup")
                messages.info(request, 'O ano letivo já existe!')
                return HttpResponseRedirect('/funcionariomanager/createAnoletivo')

            # Objeto AnoLetivo
            anoletivo = AnoLetivo()
            anoletivo.nome = name
            anoletivo.datainicio = datainicio
            anoletivo.datafim = datafim
            anoletivo.save()
            messages.info(request, 'O ano letivo foi criado com sucesso.')
            return redirect('/funcionariomanager/anoLetivo/')
    else:
        form = edit_AnoLetivo()
    return render(request, 'funcionariomanager/create_anoletivo.html', {'form': form})


def selectanoletivo():
    today = date.today()
    print(today)
    anoletivo = AnoLetivo.objects.filter(datainicio__lt=today, datafim__gt=today)
    return anoletivo[0]

###################################################################################
######### Listar Ano letivo      ##################################################
######### Autor: Gonçalo Almeida ##################################################
###################################################################################

def RenderAnoLetivo(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario").exists():
        return redirect('/requestmanager/welcome/')

    tables = AnoLetivoTable(AnoLetivo.objects.all())
    return render(request, 'funcionariomanager/list_anoletivo.html', {"table": tables})


###############################################################################
######### Edit Ano letivo   ###################################################
######### Autor: Tomás Roma ###################################################
###############################################################################

def edit_anoletivo(request, id):
    if not request.user.is_authenticated or not request.user.groups.filter(name="Funcionario"):
        return redirect('/requestmanager/welcome/')

    anoletivo = AnoLetivo.objects.get(id=id)
    if request.method == 'POST':
        form = edit_AnoLetivo(request.POST)
        if form.is_valid():
            datainicio = form.cleaned_data['datainicio']
            datafim = form.cleaned_data['datafim']

            anoi = datainicio.year
            anof = datafim.year

            if (anoi + 1 != anof):
                print("Erro Ano")
                messages.error(request, 'Os anos letivos devem ter um maximo de um ano!')
                return HttpResponseRedirect('/funcionariomanager/edit_anoLetivo/' + str(id))
            name = str(anoi) + "-" + (str(anof))[2:4]
            if AnoLetivo.objects.filter(nome=name, datainicio=datainicio, datafim=datafim).count() != 0:
                print("Erro Dup")
                messages.error(request, 'O ano letivo já existe!')
                return HttpResponseRedirect('/funcionariomanager/edit_anoLetivo/' + str(id))

            pedidosAno = Pedido.objects.filter(anoletivo=id)
            if pedidosAno.count():
                print("Erro pedido")
                messages.error(request, 'Ja exitem pedidos associados ao ano letivo.')
                return HttpResponseRedirect('/funcionariomanager/edit_anoLetivo/' + str(id))

            anoletivo.nome = name
            anoletivo.datainicio = datainicio
            anoletivo.datafim = datafim
            anoletivo.save()
            messages.info(request, 'O ano letivo foi editado com sucesso.')
            return HttpResponseRedirect('/funcionariomanager/anoLetivo/')

    form = edit_AnoLetivo(initial={
        'datainicio': anoletivo.datainicio,
        'datafim': anoletivo.datafim
    })
    context = {
        "form": form,
        "name": anoletivo.nome,
    }
    return render(request, 'funcionariomanager/edit_anoletivo.html', context)


###################################################################################
######### Delete Ano letivo     ###################################################
######### Autor: André Oliveira ###################################################
###################################################################################

def delete_anoletivo(request, id):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    anoletivo = AnoLetivo.objects.get(id=id)
    pedidosAno = Pedido.objects.filter(anoletivo=id)
    if pedidosAno.count():
        messages.error(request, 'Não foi possível eliminar o ano letivo. Já tem pedidos associados.')
        return HttpResponseRedirect('/funcionariomanager/anoLetivo/')
    if request.method == 'POST':
        anoletivo.delete()
        messages.info(request, 'O ano letivo foi eliminado com sucesso.')
        return HttpResponseRedirect('/funcionariomanager/anoLetivo/')
    return render(request, 'funcionariomanager/delete_anoletivo.html')


# Mensagem de sucesso

def sucesso_view(request, mensagem):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    return render(request, 'funcionariomanager/sucesso.html', {'message': mensagem})


def erro_view(request, mensagem):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    return render(request, 'funcionariomanager/erro.html', {'message': mensagem})


class app_render(SingleTableMixin, django_filters.views.FilterView):
    model = Pedido
    table_class = PedidoTable
    filterset_class = PedidoFilter
    template_name = 'funcionariomanager/app.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:

project/funcionariomanager/templates/funcionariomanager/confirmation-page.html
{% extends 'funcionariomanager/layout.html' %}
{% block content %}
<p style="text-align:center; font-size: larger;"><strong>{{ confirm_question }}</strong></p><br>
<div class="center" style="text-align:center">
  <form action="" method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input class="button is-primary" type="submit" value="Sim">
        <a href="{%url 'funcionariomanager:app_render' user.id%}" class="button is-primary">Não</a>
  </form>
</div>
{% endblock content %}

project/funcionariomanager/templates/funcionariomanager/consult_pedidoHorario.html
{% extends 'funcionariomanager/layout.html' %}
{% load static %}

{% block content %}
<div class="has-text-centered">
    <h1 style="text-align: center; font-weight: bold;">Consultar Pedido de horario</h1>
    <div id="table">
        <div class="block">
            <label class="label">Assunto</label>
            <input disabled name="assunto" :value=[[pedido_principal.assunto]]>
            <label class="label">Descrição</label>
            <input disabled name="descricao" :value=[[pedido_principal.descricao]]>
            <label class="label">Data Alvo</label>
            <input disabled type="date" name="descricao" :value=[[pedido_principal.dataalvo]]>
        </div>

        <div id="table" class="block columns is-centered">
            <div class="column">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width:10%">Horario</th>
                            <th style="width:10%">Alteração</th>
                            <th style="width:10%">Data Origem</th>
                            <th style="width:10%">Hora Origem</th>
                            <th style="width:10%">Data Mundaça</th>
                            <th style="width:10%">Hora Mundaça</th>
                            <th style="width:10%">Descrição</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="i in n" :key="i">
                            <td>
                                <div class="select">
                                    <select disabled :name="'acao' + i"
                                        v-model="tipopedidohorarioid_init[tipopedidohorarioid[i-1]-1]">
                                        <option v-for="(option, index) in tipopedidohorarioid_init" :key="index"
                                            :value=option> [[ option ]]
                                        </option>
                                    </select>
                                </div>
                            </td>

                            <td>
                                <div class="select">
                                    <select disabled :name="'turma' + i"
                                        v-model="tipoalteracaohorarioid_init[tipoalteracaohorarioid[i-1]-1]">
                                        <option v-for="(option, index) in tipoalteracaohorarioid_init" :key="index"
                                            :value=option> [[ option ]]
                                        </option>
                                    </select>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'data_origem' + i" type="date"
                                        :value=[[pedidos[i-1].dataorigem]]>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'hora_origem' + i" :value=[[pedidos[i-1].horaorigem]]
                                        type="time">
                                </div>
                            </td>

                            <td>
                                <div>
                                    <labe l class="">
                                        <input disabled :name="'data_mudanca' + i" type="date"
                                            :value=[[pedidos[i-1].datamudanca]]>
                                        </label>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'hora_mudanca' + i" :value=[[pedidos[i-1].horamudanca]]
                                        type="time">
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <textarea disabled :name="'descricao' + i" style="resize: none" rows="2" cols="17"
                                        :value=[[pedidos[i-1].descricao]]></textarea>
                                </div>
                            </td>


                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% if pendente and check %}
    <a href="{% url 'funcionariomanager:link_pedido' id %}" class="button is-primary"> Associar-se </a>
    {% endif %}

    {% if resolvido and check %}
    <a href="{% url 'funcionariomanager:resolve_pedido' id %}" class="button is-success">Aceitar</a>
    <a href="{% url 'funcionariomanager:desassocia_pedido' id %}" class="button is-warning">Desassociar</a>
    <a href="{% url 'funcionariomanager:cancela_pedido' id %}" class="button is-danger">Rejeitar</a>
    {% endif %}
    <input class="button is-primary" type=button value="Voltar" onClick="javascript:history.go(-1);">
</div>
</form>

<script>
    var app = new Vue({

        delimiters: ["[[", "]]"],
        el: '#table',
        data() {
            return {
                tipopedidohorarioid: [],
                tipopedidohorarioid_init: [],
                tipoalteracaohorarioid: [],
                tipoalteracaohorarioid_init: [],


                pedidos: [],
                indexes: [],
                pedido_principal: {},
                n: 1
            }
        },
        async created() {
            console.log("sakjdklasmd")
            await this.fetchData();
            this.tipopedidohorarioid_init = ['Preparação', 'Alteração'];
            this.tipoalteracaohorarioid_init = ['Pontual', 'Permanente'];
            this.pedidos.forEach(p => this.tipopedidohorarioid.push(p.tipopedidohorarioid));
            this.pedidos.forEach(p => this.tipoalteracaohorarioid.push(p.tipoalteracaohorarioid));
            console.log(this.pedidos[1].horaorigem)
            this.pedidos.forEach(element => {
                element.horaorigem = (element.horaorigem).substring(0, 5)
                element.horamudanca = (element.horamudanca).substring(0, 5)
            });
            console.log(this.pedidos[1].horaorigem)

            this.n = this.pedidos.length
        },
        methods: {
            async fetchData() {
                pathname = window.location.pathname.split('/')
                id = pathname[pathname.length - 1]
                this.pedidos = await axios.get('http://127.0.0.1:8000/api/pedido_horario/' + id)
                this.pedidos = this.pedidos.data
                this.pedido_principal = await axios.get('http://127.0.0.1:8000/api/pedido/' + id)
                this.pedido_principal = this.pedido_principal.data
            },
            addLine() {
                this.n++
                this.indexes.push(this.n)
            },
            removeLine(i) {
                this.indexes = this.indexes.filter((x) => x != i);
                this.n--;
            },

        },
    })
</script>

{% endblock content %}

project/funcionariomanager/templates/funcionariomanager/create_anoletivo.html
{% extends 'funcionariomanager/layout.html' %}
{% block content %}
<h1 style="text-align: center; font-weight: bold; font-size: larger;">Criar Ano Letivo</h1>
<br>
<div>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <span style="font-weight: bolder; font-size: medium;">Selecione as datas do ano letivo:</span><br>
            Data Inicio: {{form.datainicio}} <br><br>
            Data Fim: {{form.datafim}}
            
            <br><br>
            <input class="button" type="submit" value="Submit">
        </form>
    </div>
    <div>    
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}, style="color: red;">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock content %}

project/funcionariomanager/templates/funcionariomanager/delete_anoletivo.html
{% extends 'funcionariomanager/layout.html' %}
{% block content %}
<p style="text-align:center"><strong>Deseja mesmo apagar?</strong></p><br>
<div class="file">
    <div>    
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}, style="color: green;">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
<br>
<br>
<div class="center" style="text-align:center">
    <form action="" method = "POST" enctype="multipart/form-data">
          {% csrf_token %}
          <input class="button is-primary" type="submit" value="Sim">
          <a href="{%url 'funcionariomanager:list_anoletivo'%}" class="button is-primary">Não</a>
    </form>
  </div>
{% endblock content %}

project/funcionariomanager/templates/funcionariomanager/navbar.html
{% load static %}
{% load auth_extras %}
<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        {% if user.is_authenticated %}
            <a class="navbar-item logo" href="{% url 'funcionariomanager:app_render' user.id %}">
                <img src="{% static 'img/logo-navbar.png' %}" alt="UALG">
            </a>
        {% endif %}
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            {% if user.is_authenticated and user|has_group:"ProfessorUniversitario" %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Pedidos</a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'requestmanager:list_outros' %}" class="navbar-item">Pedidos Outros</a>
                        <a href="{% url 'requestmanager:list_horario' %}" class="navbar-item">Pedido Horário</a>
                        <a href="{% url 'requestmanager:list_salas' %}" class="navbar-item">Pedido Sala</a>
                        <a href="{% url 'requestmanager:list_unidadeCurricular' %}" class="navbar-item">Pedido Unidade
                            Curricular</a>
                    </div>
                </div>
            {% endif %}

            {% if user.is_authenticated and user|has_group:"Funcionario" %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Import/Export</a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'datamanager:export_pedidos_xls' %}" class="navbar-item">Export Pedidos</a>
                        <a href="{% url 'datamanager:import_RUC' %}" class="navbar-item">Import RUC</a>
                        <a href="{% url 'datamanager:import_DSD' %}" class="navbar-item">Import DSD</a>
                        <a href="{% url 'datamanager:import_salas' %}" class="navbar-item">Import Salas</a>
                        <a href="{% url 'datamanager:import_DOCENTE' %}" class="navbar-item">Import DOCENTE</a>
                    </div>
                </div>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Funcionários</a>
                    <div class="navbar-dropdown">
                        {% comment %} <a href="{% url 'funcionariomanager:emailPCP' %}" class="navbar-item">Contactar PCP</a> {% endcomment %}
                        <a href="{% url 'funcionariomanager:create_anoletivo' %}" class="navbar-item">Criar Ano
                            Letivo</a>
                        <a href="{% url 'funcionariomanager:list_anoletivo' %}" class="navbar-item">Listar Anos
                            Letivos</a>
                    </div>
                </div>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Estatisticas</a>
                    <div class="navbar-dropdown">
                        <a href="{% url 'statmanager:funcionarios_stats' %}" class="navbar-item"> Estatisticas de funcionarios </a>
                        <a href="{% url 'statmanager:chart_pedidos' %}" class="navbar-item"> Estatisticas de pedidos </a>
                    </div>
                </div>
            {% endif %}
        </div>


        <div class="navbar-end">
            <div class="navbar-item">
                {% if user.is_authenticated %}
                    <a class="navbar-item">
                        Hello {{ user.first_name }} {{ user.last_name }}
                    </a>
                {% else %}
                    <a class="navbar-item" href="{% url 'authmanager:register_user' %}">
                        Register
                    </a>
                {% endif %}
                {% if user.is_authenticated %}
                    <a class="navbar-item" href="{% url 'authmanager:logout' %}">
                        Logout
                    </a>
                {% else %}
                    <a class="navbar-item" href="{% url 'authmanager:login' %}">
                        Login
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>