project/authmanager/urls.py
from django.urls import path
from authmanager.views import *


urlpatterns = [
    #path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path("login/", login_action, name="login"),
    path('mensagem/<int:id>', mensagem,name='mensagem'),   
    
    path('escolher_perfil/', escolher_perfil, name='escolher_perfil'),
    path('register_user/<int:id>', criar_utilizador, name='register_user'),
    path('concluir_registo/<int:id>', concluir_registo, name='concluir_registo'),
    
    path('ajax/load-departamentos/', load_departamentos, name='ajax_load_departamentos'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('api-auth', include('rest_framework.urls')),
    path('api/', include('todo_api.urls')),
    path('funcionariomanager/', include(('funcionariomanager.urls', 'funcionariomanager'), namespace='funcionariomanager')),
    path('datamanager/', include(('datamanager.urls', 'datamanager'), namespace='datamanager')),
    path('requestmanager/', include(('requestmanager.urls', 'requestmanager'), namespace='requestmanager')),
    path('statmanager/', include(('statmanager.urls', 'statmanager'), namespace='statmanager')),
    path('authmanager/', include(('authmanager.urls', 'authmanager'), namespace='authmanager')),
    #path('utilizadores/', include(('utilizadores.urls', 'utilizadores'), namespace='utilizadores')),
    path('admin/', admin.site.urls),
]

project/requestmanager/urls.py
from django.urls import path

from requestmanager.views import *

urlpatterns = [
    path('pedidoHorario/', create_pedidoHorario, name='create_pedidoHorario'),
    path('editarPedidoHorario/<int:pdd_id>', edit_pedidoHorario, name='edit_pedidoHorario'),
    # path('apagarPedidoHorario/<int:pdd_id>', delete_pedidoHorario, name='delete_pedidoHorario'),
    path('createpedidooutro/', create_pedidooutro, name='create_pedidooutro'),
    # path('deletepedidooutro/', delete_pedidooutro, name='delete_pedidooutro'),
    path('editpedidooutro/<int:pdd_id>', edit_pedidooutro, name='edit_pedidooutro'),
    path('create_pedidoUnidadeCurricular/', create_unidadeCurricular, name='create_unidadeCurricular'),
    # path('delete_pedidoUnidadeCurricular/<int:pedidoID>', delete_unidadeCurricular, name='delete_unidadeCurricular'),
    path('edit_pedidoUnidadeCurricular/<int:pedidoID>', edit_unidadeCurricular, name='edit_unidadeCurricular'),
    path('list_pedidoUnidadeCurricular/<int:user_id>', app_renderUC.as_view(template_name="requestmanager/list_unidadecurricular.html"), name='list_unidadeCurricular'),
    path('list_salas/<int:user_id>', app_renderSalas.as_view(template_name="requestmanager/list_salas.html"), name='list_salas'),
    path('list_horario/<int:user_id>', app_renderHorario.as_view(template_name="requestmanager/list_horario.html"), name='list_horario'),
    path('list_outros/<int:user_id>', app_renderOutros.as_view(template_name="requestmanager/list_outros.html"), name='list_outros'),
    # path('delete_pedidoSala/', delete_pedidoSala, name='delete_pedidoSala'),
    path('create_pedidoSala/', create_pedidoSala, name='create_pedidoSala'),
    path('edit_pedidoSala/<int:pedidoID>', edit_pedidoSala, name='edit_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('delete_pedido/<int:pdd_id>', delete_pedido, name='delete_pedido'),
    path('app/<int:user_id>', app_render.as_view(template_name="requestmanager/app.html"), name='app_render'),
    path('consult_pedidoSala/<int:pedidoID>', consult_pedidoSala, name='consult_pedidoSala'),
    path('consult_pedido/<int:pdd_id>', consult_pedido, name='consult_pedido'),
    path('consult_pedidoHorario/<int:pdd_id>', consult_pedidoHorario, name='consult_pedido'),
    path('consult_pedidoUnidadeCurricular/<int:id>', consult_unidadeCurricular, name='consult_pedidoUC'),
    path('delete_pedido/<int:id>', delete_pedido, name='delete_pedido'),
    path('sucesso/', sucesso_view, name='sucesso'),
    path('welcome/', welcome_page_view, name='welcome_page')
]

project/requestmanager/views.py
import datetime
import math
from django.http import HttpResponseRedirect

from django.shortcuts import render, redirect
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from .filters import *
from .forms import *
from .tables import *
from .models import *

from django.contrib.auth.models import Group
from django.contrib import messages


#################################################
##### Ordem:                                #####
#####      -Pedido de Unidade Curricular    #####
#####      -Pedido de Sala de Aula          #####
#####      -Pedido de Horários              #####
#####      -Pedido Outros                   #####
#####      -List                            #####
#####      -App Render                      #####
#################################################

def selectanoletivo():
    today = date.today()
    anoletivo = AnoLetivo.objects.filter(datainicio__lte=today, datafim__gte=today)
    return anoletivo[0]


#################################################################################
##### PEDIDO UNIDADE CURRICULAR #################################################
##### Autor: André Oliveira     #################################################
#################################################################################

# TODO - VERIFICAR SE NAO HA COISAS VAZIAS

# CREATE
def create_unidadeCurricular(request):
    if not request.user.is_authenticated or not request.user.groups.filter(name='ProfessorUniversitario').exists():
        return redirect('/requestmanager/welcome/')
    #
    import datetime
    min_date = (datetime.datetime.today()).date().isoformat()
    max_date = selectanoletivo().datafim.isoformat()

    if request.method == 'POST':
        formpedido = PedidoForm(request.POST)
        # if formpedido.is_valid():
        assunto = request.POST.get('assunto')
        descricao = request.POST.get('descricao')
        data = request.POST.get('data')

        if assunto.strip() == "" or descricao.strip() == "" or data == "":
            errors = "Todos os campos devem ser preenchidos."
            return render(request, 'requestmanager/create_unidadecurricular.html',
                          {'form': formpedido, 'errors': errors, 'min_date': min_date, 'max_date': max_date})

        ##### ERROR CHECKING ###
        # date_1 = datetime.strptime(data, "%Y-%m-%d")
        # today_date = datetime.strptime(str(datetime.today()).split(' ')[0], "%Y-%m-%d")
        # if date_1 < today_date or date_1 > datetime.strptime(str(selectanoletivo().datafim).split(' ')[0],
        #                                                      "%Y-%m-%d"):
        #     errors = "A data-alvo selecionada deve estar entre o dia atual e a data final do ano letivo atual."
        #     # errors = "A data-alvo selecionada deve ser a do pedido mais próximo da data atual."
        #     return render(request, 'requestmanager/create_unidadecurricular.html',
        #                   {'formpedido': formpedido, 'errors': errors, 'min_date': min_date, 'max_date': max_date})
        docente = ProfessorUniversitario.objects.get(pk=request.user.id)

        pedido = Pedido(docente=docente, assunto=assunto, descricao=descricao, dataalvo=data,
                        estado_id=1, tipo=TipoPedido.objects.get(pk=3), anoletivo=selectanoletivo())

        objects = []
        size = math.ceil(((len(list(request.POST.dict()))) - 4) / 5)
        for i in range(0, size):
            acao_pedido = request.POST["acao" + str(i)]
            turma_pedido = request.POST['turma' + str(i)]
            unidade_pedido = request.POST['unidade' + str(i)]
            assunto_pedido = request.POST['assunto' + str(i)]
            pedido_uc = Pedidouc(acao=Acao.objects.get(pk=acao_pedido),
                                 tipoturmaid=TipoTurma.objects.get(pk=turma_pedido),
                                 unidadecurricularid_id=unidade_pedido, assunto=assunto_pedido,
                                 pedido_ptr_id=pedido)
            objects.append(pedido_uc)

        pedido.save()
        for p in objects:
            p.save()

        messages.info(request, 'Pedido criado com sucesso')
        return redirect('/requestmanager/app/' + str(request.user.id))
    else:
        formpedido = PedidoForm()
        return render(request, 'requestmanager/create_unidadecurricular.html',
                      {'form': formpedido, 'min_date': min_date, 'max_date': max_date})


# EDIT
def edit_unidadeCurricular(request, pedidoID):
    if not request.user.is_authenticated or not request.user.groups.filter(name='ProfessorUniversitario').exists():
        return redirect('/requestmanager/welcome/')

    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')
    #
    import datetime
    min_date = (datetime.datetime.today()).date().isoformat()
    max_date = selectanoletivo().datafim.isoformat()

    pedido = Pedido.objects.get(id=pedidoID)
    pedidouc = Pedidouc.objects.filter(pedido_ptr_id_id=pedidoID)
    error_data = False
    if request.method == 'POST':
        form = edit_unidadesCurriculares(request.POST)
        if form.is_valid():
            descricao = request.POST.get('descricao')
            assunto = request.POST.get('assunto')
            data = request.POST.get('data')

            pedido.descricao = descricao
            pedido.assunto = assunto
            pedido.dataalvo = data

            ids_atualizados = []  # Guarda quais os ids dos pedidodinhos que foram alterados e criados
            objects = []
            size = math.ceil(((len(list(request.POST.dict()))) - 4) / 5)
            for i in range(0, size):
                acao_pedido = request.POST["acao" + str(i)]
                turma_pedido = request.POST['turma' + str(i)]
                unidade_pedido = request.POST['unidade' + str(i)]
                assunto_pedido = request.POST['assunto' + str(i)]

                if acao_pedido.strip() == "" or turma_pedido.strip() == "" or unidade_pedido == "" or assunto_pedido == "":
                    errors = "Todos os campos devem ser preenchidos."
                    return render(request, 'requestmanager/edit_unidadecurricular.html',
                                  {'form': form, 'errors': errors, 'min_date': min_date, 'max_date': max_date})

                # Se nao há mais pedidodinho, significa que é um pedidodinho novo retornando o ultimo id da tabela + 1
                try:
                    ultimo_pedido_uc = Pedidouc.objects.last().id + 1
                except:
                    ultimo_pedido_uc = 1

                last_pedidodinho = request.POST.get("pedidodinho" + str(i), ultimo_pedido_uc)
                ids_atualizados.append(str(last_pedidodinho))

                old_pedidouc, iscreated = Pedidouc.objects.get_or_create(id=last_pedidodinho)
                old_pedidouc.unidadecurricularid = Unidadecurricular.objects.get(id=unidade_pedido)
                old_pedidouc.acao = Acao.objects.get(id=acao_pedido)
                old_pedidouc.tipoturmaid = TipoTurma.objects.get(pk=turma_pedido)
                old_pedidouc.assunto = assunto_pedido
                old_pedidouc.pedido_ptr_id = pedido
                objects.append(old_pedidouc)

            pedido.save()

            for p in objects:
                p.save()

            for pedido in pedidouc:
                if str(pedido.id) not in ids_atualizados:
                    pedido.delete()
            messages.info(request, 'Pedido editado com sucesso')
            return redirect('/requestmanager/app/' + str(request.user.id))
        return render(request, 'requestmanager/consult_unidadecurricular.html',
                      {'id': pedidoID, 'min_date': min_date, 'max_date': max_date})

    else:
        form = PedidoForm(initial={'assunto': pedido.assunto, 'descricao': pedido.descricao, 'data': pedido.dataalvo})
    context = {
        'form': form, 'min_date': min_date, 'max_date': max_date
    }
    return render(request, 'requestmanager/edit_unidadecurricular.html', context)


# DELETE
def delete_unidadeCurricular(request, pedidoID):
    if not request.user.is_authenticated or not request.user.groups.filter(name='ProfessorUniversitario').exists():
        return redirect('/requestmanager/welcome/')

    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    if request.method == 'POST':
        form = delete_unidadesCurriculares(request.POST)
        if form.is_valid():
            pedidouc = Pedidouc.objects.get(pk=pedidoID)
            id = request.POST.get('id')
            pedidouc.delete()
            print("apagado")
    else:
        form = delete_unidadesCurriculares()

    context = {
        'form': form,
        'list': list(Pedidouc.objects.raw(
            'SELECT * FROM Pedidouc LEFT JOIN Unidadecurricular ON Pedidouc.unidadecurricularid = Unidadecurricular.id'))
    }
    return render(request, 'requestmanager/delete_unidadecurricular.html', context)


# CONSULT
def consult_unidadeCurricular(request, id):
    if not request.user.is_authenticated:
        return redirect('/requestmanager/welcome/')

    pedido = Pedido.objects.get(id=id)
    form = PedidoForm(initial={'assunto': pedido.assunto, 'descricao': pedido.descricao, 'data': pedido.dataalvo})
    state = pedido.estado
    pendente = EstadoPedido.objects.get(pk=1)
    resolvido = EstadoPedido.objects.get(pk=3)
    context = {
        'id': id,
        'form': form,
        'change': state == pendente

    }
    return render(request, 'requestmanager/consult_unidadecurricular.html', context)


##########################################################################################
######### PEDIDO SALA DE AULA      #######################################################
######### Autor: António Madureira #######################################################

project/requestmanager/templates/requestmanager/confirmation-page.html
{% extends 'funcionariomanager/layout.html' %}
{% block content %}
<p style="text-align:center"><strong>{{ confirm_question }}</strong></p><br>
<div class="center" style="margin:auto; margin-right: 50%; margin-left: 50%">
  <form action="" method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input class="button is-primary" type="submit" value="Sim">
        <a href="{%url 'requestmanager:app_render'%}" class="button is-primary">Não</a>
  </form>
</div>
{% endblock content %}

project/requestmanager/templates/requestmanager/consult_pedidoHorario.html
{% extends 'requestmanager/layout.html' %}
{% load static %}

{% block content %}
    <div class="has-text-centered">
        <h1 style="text-align: center; font-weight: bold; font-size: larger;">Consultar Pedido de Horário</h1>
        <div id="table">
            <div class="block">
                <label class="label">Assunto</label>
                <input disabled name="assunto" :value=[[pedido_principal.assunto]]>
                <label class="label">Descrição</label>
                <input disabled name="descricao" :value=[[pedido_principal.descricao]]>
                <label class="label">Data Alvo</label>
                <input disabled type="date" name="descricao" :value=[[pedido_principal.dataalvo]]>
            </div>

            <div id="table" class="block columns is-centered">
                <div class="column">
                    <table class="table">
                        <thead>
                        <tr>
                            <th style="width:10%">Ação</th>
                            <th style="width:10%">Alteração</th>
                            <th style="width:10%">Data Origem</th>
                            <th style="width:10%">Hora Origem</th>
                            <th style="width:10%">Data Mundança</th>
                            <th style="width:10%">Hora Mundança</th>
                            <th style="width:10%">Descrição</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr v-for="i in n" :key="i">
                            <td>
                                <div class="select">
                                    <select disabled :name="'acao' + i" v-model="acoes_init[acoes[i-1]-1]">
                                        <option v-for="(option, index) in acoes_init" :key="index" :value=option> [[
                                            option ]] </option>
                                    </select>
                                </div>
                            </td>

                            <td>
                                <div class="select">
                                    <select disabled :name="'turma' + i"
                                            v-model="tipoalteracaohorarioid_init[tipoalteracaohorarioid[i-1]-1]">
                                        <option v-for="(option, index) in tipoalteracaohorarioid_init" :key="index"
                                                :value=option> [[ option ]]
                                        </option>
                                    </select>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'data_origem' + i" type="date"
                                           :value=[[pedidos[i-1].dataorigem]]>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'hora_origem' + i" :value=[[pedidos[i-1].horaorigem]]
                                           type="time">
                                </div>
                            </td>

                            <td>
                                <div>
                                    <labe l class="">
                                        <input disabled :name="'data_mudanca' + i" type="date"
                                               :value=[[pedidos[i-1].datamudanca]]>
                                        </label>
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <input disabled :name="'hora_mudanca' + i" :value=[[pedidos[i-1].horamudanca]]
                                           type="time">
                                </div>
                            </td>

                            <td>
                                <div class="">
                                    <textarea disabled :name="'descricao' + i" style="resize: none" rows="2" cols="17"
                                              :value=[[pedidos[i-1].descricao]]></textarea>
                                </div>
                            </td>


                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% if pendente %}
            <a href="{% url 'requestmanager:edit_pedidoHorario' id %}" class="button is-primary">Editar</a>
            <a href="{% url 'requestmanager:delete_pedido' id %}" class="button is-danger">Eliminar</a>
        {% endif %}
        <input class="button is-primary" type=button value="Voltar" onClick="javascript:history.go(-1);">
    </div>
    </form>

    <script>
        var app = new Vue({

            delimiters: ["[[", "]]"],
            el: '#table',
            data() {
                return {
                    acoes: [],
                    acoes_init: [],
                    tipopedidohorarioid: [],
                    tipopedidohorarioid_init: [],
                    tipoalteracaohorarioid: [],
                    tipoalteracaohorarioid_init: [],


                    pedidos: [],
                    indexes: [],
                    pedido_principal: {},
                    n: 1
                }
            },
            async created() {
                console.log("sakjdklasmd")
                await this.fetchData();
                this.tipoalteracaohorarioid_init = ['Pontual', 'Permanente'];
                this.acoes_init = ['Criar', 'Apagar', 'Alterar'];
                this.pedidos.forEach(p => this.acoes.push(p.acao));
                this.pedidos.forEach(p => this.tipoalteracaohorarioid.push(p.tipoalteracaohorarioid));
                this.pedidos.forEach(element => {
                    element.horaorigem = (element.horaorigem).substring(0, 5)
                    element.horamudanca = (element.horamudanca).substring(0, 5)
                });
                this.n = this.pedidos.length
                console.log(this.n)
                //console.log(this.pedidos[1].horaorigem)

            },
            methods: {
                async fetchData() {
                    pathname = window.location.pathname.split('/')
                    id = pathname[pathname.length - 1]
                    this.pedidos = await axios.get('http://127.0.0.1:8000/api/pedido_horario/' + id)
                    this.pedidos = this.pedidos.data
                    this.pedido_principal = await axios.get('http://127.0.0.1:8000/api/pedido/' + id)
                    this.pedido_principal = this.pedido_principal.data
                },
                addLine() {
                    this.n++
                    this.indexes.push(this.n)
                },
                removeLine(i) {
                    this.indexes = this.indexes.filter((x) => x != i);
                    this.n--;
                },

            },
        })
    </script>

{% endblock content %}

project/requestmanager/templates/requestmanager/consult_pedidosala.html
{% extends 'requestmanager/layout.html' %}
{% load static %}

{% block content %}
<form class="has-text-centered" method="post" id="form">
    {% csrf_token %}
    <div id="table">
        <div v-if="isDoneFetching">
            <div class="block">
                <h1 style="text-align: center; font-weight: bold; font-size: larger;">Consultar Pedido de Sala</h1>
                <label class="label">Assunto</label>
                [[pedido_principal.assunto]]
                <label class="label">Descrição</label>
                [[pedido_principal.descricao]]
                <label class="label">Data Alvo</label>
                [[pedido_principal.dataalvo]]
                <br><br>
            </div>

            <div class="block columns">
                <div class="column">
                    <table class="table">
                        <thead>
                            <tr>
                                <th style="width:10%">Ação</th>
                                <th style="width:10%">Lotação</th>
                                <th style="width:10%">Data</th>
                                <th style="width:10%">Hora de Inicio</th>
                                <th style="width:10%">Hora de Fim</th>
                                <th style="width:10%">Ocasião</th>
                                <th style="width:10%;">Tipo de sala</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="i in n" :key="i">
                                <td>
                                    <div class="select">
                                        <select disabled :name="'acao' + i" v-model="acoes_init[acoes[i-1]-1]">
                                            <option v-for="(option, index) in acoes_init" :key="index" :value=option> [[
                                                option ]] </option>
                                        </select>
                                    </div>
                                </td>
                                <td>
                                    <input disabled v-if="i <= pedidos.length" type="hidden" :name="'pedidodinho' + i"
                                        :value="[[pedidos[i-1].id]]">
                                    <label>
                                        <input disabled v-if="i <= pedidos.length" :name="'lotacao' + i"
                                            :value=[[pedidos[i-1].alunosprevistos]] type="number" min="1" max="475">
                                        <input disabled v-else :name="'lotacao' + i" type="number">
                                    </label>
                                </td>
                                <td>
                                    <label>
                                        <input disabled v-if="i <= pedidos.length" type="date" :name="'data' + i"
                                            :value=[[pedidos[i-1].data]]>
                                        <input disabled v-else :name="'data' + i" type="date">
                                    </label>
                                </td>
                                <td>
                                    <div>
                                        <label>
                                            <input disabled v-if="i <= pedidos.length" :name="'horainicio' + i"
                                                :value=[[pedidos[i-1].horainicio]] type="time"></input>
                                            <input disabled v-else :name="'horainicio' + i" type="time"></input>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <div>
                                        <label>
                                            <input disabled v-if="i <= pedidos.length" :name="'horafim' + i"
                                                :value=[[pedidos[i-1].horafim]] type="time"></input>
                                            <input disabled v-else :name="'horafim' + i" type="time"></input>
                                        </label>
                                    </div>
                                </td>
                                <td>
                                    <div class="select">
                                        <select disabled :name="'tipos' + i">
                                            <template v-for="(option, index) in tipos" :key="index">
                                                <option
                                                    v-if="i <= pedidos.length && option.id == pedidos[i-1].tipopedidosalaid"
                                                    selected :value=option.id>
                                                    [[option.nome]] </option>
                                                <option v-else :value=option.id>
                                                    [[option.nome]] </option>
                                            </template>
                                        </select>
                                    </div>
                                </td>
                                <td>
                                    <div class="select" >
                                        <select disabled :name="'tiposala' + i">
                                            <template v-for="(option, index) in tiposala" :key="index">
                                                <option
                                                    v-if="i <= pedidos.length && option.id == pedidos[i-1].categoriasalaid"
                                                    selected :value=option.id>
                                                    [[option.nome]] </option>
                                                <option v-else :value=option.id>
                                                    [[option.nome]] </option>
                                            </template>
                                        </select>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% if pendente %}
    <a href="{% url 'requestmanager:edit_pedidoSala' id %}" class="button is-primary">Editar</a>
    <a href="{% url 'requestmanager:delete_pedido' id %}" class="button is-danger">Eliminar</a>
    {% endif %}
    <input class="button is-primary" type=button value="Voltar" onClick="javascript:history.go(-1);">
</form>

<script>
    var app = new Vue({

        delimiters: ["[[", "]]"],
        el: '#table',
        data() {
            return {
                acoes: [],
                tipos: [],
                acoes_init: [],
                pedido_principal: {},
                pedidos: [],
                tiposala: [],
                n: 2,
                isDoneFetching: false
            }
        },
        async created() {
            await this.fetchData();
            this.acoes_init = ['Criar', 'Apagar', 'Alterar'];
            this.pedidos.forEach(p => this.acoes.push(p.acao));
            this.isDoneFetching = true;
            console.log(this.pedidos)
        },
        methods: {
            async fetchData() {
                pathname = window.location.pathname.split('/')
                id = pathname[pathname.length - 1]
                this.unidade = await axios.get('http://127.0.0.1:8000/api/uc_unidadecurricular/' + 3)
                this.unidade = this.unidade.data
                this.tiposala = await axios.get('http://127.0.0.1:8000/api/categoriaSala/')
                this.tiposala = this.tiposala.data
                this.pedidos = await axios.get('http://127.0.0.1:8000/api/pedido_sala/' + id)
                this.pedidos = this.pedidos.data
                this.tipos = await axios.get('http://127.0.0.1:8000/api/tipopedidosala')
                this.tipos = this.tipos.data
                this.pedidos.forEach(element => {
                    element.horainicio = (element.horainicio).substring(0, 5)
                    element.horafim = (element.horafim).substring(0, 5)
                });
                this.pedido_principal = await axios.get('http://127.0.0.1:8000/api/pedido/' + id)
                this.pedido_principal = this.pedido_principal.data
                this.n = this.pedidos.length
            },

            addLine() {
                this.n++
                //this.indexes.push(this.n)
            },
            removeLine(i) {
                //this.indexes = this.indexes.filter((x) => x != i);
                this.n--;
            },

        },
    })
</script>

{% endblock content %}

project/requestmanager/templates/requestmanager/popup.html
<div id="msg" class="dialog modal">
    <div class="modal-background"></div>
    <div class="modal-card animation-content">
        <section class="modal-card-body is-titleless" style="border-top-left-radius: 6px; border-top-right-radius: 6px;">
            <div class="media">
                <div class="media-content">
                    <p id='text-00'></p>
                </div>
            </div>
        </section>
        <footer class="modal-card-foot">
            <button onclick="alert.cancelar()" class="button" id='dialog-cancel'>Cancelar</button>
            <button onclick="alert.confirmar()" class="button is-success" id='dialog-confirm'>Confirmar</button>
        </footer>
    </div>
</div>